import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    // Auth & Common
    laminatingDough: "Laminating Dough",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    activeSubscriptionsCustomerDesc: "Your active repeating weekly orders. Our bakers automatically prepare these bakes every cycle!",
    connectingOven: "Connecting to Artisan Oven Core...",
    laPetiteFarine: "La Petite Farine",
    microbakeryMgmt: "Microbakery Management Core",
    emailAddr: "Email Address",
    password: "Password",
    fullName: "Full Name",
    registerAccount: "Register Account",
    authenticateSession: "Authenticate Session",
    signInWithGoogle: "Sign in with Google",
    registerWithGoogle: "Register with Google",
    alreadyRegistered: "Already registered? Log in here",
    newBakeryClient: "New bakery client? Create an account",
    awaitingApproval: "Awaiting Baker Approval",
    awaitingApprovalDesc: "Welcome to La Petite Farine, {name}! Your registration is currently in queue. To protect fresh on-demand batch scaling, our head baker approves customer access manually.",
    assignedStatus: "Assigned Status",
    checkStatusAgain: "Check status again",
    accessRestricted: "Access Restricted",
    accessRestrictedDesc: "Regrettably, your customer registration has been declined. If you believe this is in error, please consult the bakery administration directly.",
    logout: "Log Out",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    statusText: "Status",
    // Admin Sidebar
    adminCore: "Microbakery Admin Core",
    overview: "Overview",
    userApprovals: "User Approvals",
    productRecipes: "Product & Recipes",
    weeklyMenuPlanner: "Weekly Menu Planner",
    bakingOrders: "Baking Orders",
    productionBatches: "Production Batches",
    standingSubscriptions: "Standing Subscriptions",
    bakeryOwner: "Bakery Owner",
    // Admin Overview
    bakeryDashboard: "Bakery Dashboard",
    realtimeOps: "Real-time baking operations and flour requirements",
    refreshEngine: "Refresh Engine",
    totalActiveOrders: "Total Active Orders",
    totalProductsBaking: "Total Products Baking",
    ordersLabel: "orders",
    itemsLabel: "items",
    cumulFlourKg: "Cumulative Flour",
    totalEstDoughWeight: "Est. Dough Weight",
    readyForOven: "Ready for oven",
    unapprovedSignups: "Unapproved Signups",
    awaitingApprovalLabel: "Awaiting approval",
    productsCatalog: "Products Catalog",
    activeCategories: "Active categories",
    weeklyBatches: "Weekly Batches",
    lockedProductionRuns: "Locked production runs",
    autoIngredientCalc: "Automatic Ingredient Calculation Engine",
    dynamicSummary: "Dynamic Summary",
    allActiveOrders: "All Active Orders (Uncompleted)",
    filterByBatch: "Filter by Batch",
    flourRequired: "Flour Required",
    waterRequired: "Water Required",
    starterLeaven: "Starter / Leaven",
    fineSeaSalt: "Fine Sea Salt",
    flourTypesBreakdown: "Flour Types Breakdown",
    richEnrichment: "Rich enrichment Ingredients & Fillings",
    missingFormulas: "Missing Formulas / Recipes:",
    missingFormulasDesc: "Baking counts for {recipes} cannot be fully compiled because their variant recipes are undefined. Go to Products and specify recipes.",
    estCumulativeDough: "Estimated Cumulative Dough Mass:",
    bakeListBreakdown: "Bake List Breakdown",
    noActiveCalculations: "No active calculations. Add confirmed orders.",
    noBakingBreakdowns: "No baking breakdowns for this week.",
    // Bulk mixing container card
    bulkMixingTitle: "🥣 Single-Bowl Bulk Mixing Batches",
    bulkMixingDesc: "Group different sizes of the same product recipe into one giant batch container for bulk fermentation and portioning.",
    totalFlour: "Total Flour Weight",
    totalWater: "Total Water Weight",
    totalStarter: "Total Starter Weight",
    totalSalt: "Total Sea Salt Weight",
    totalBatchWeight: "Total Combined Batch Weight",
    scalingInstructions: "⚖️ Scaling & Portioning Instructions",
    scalingInstructionsDesc: "Once fermentation is complete, divide this single bulk dough container into the following portions:",
    portionSize: "Portion {qty}x {size} loaves: Cut at {weight}g total dough mass",
    orGramsFlour: "({flour}g flour base per loaf)",
    noBulkMixing: "No bulk mixing groups currently calculated. Add active orders first.",
    // Admin User Approvals
    customerRegApprovals: "Customer Registration Approvals",
    customerRegApprovalsDesc: "Only approved registrations can access weekly menus and place bread orders.",
    customerName: "Customer Name",
    emailAddressTable: "Email Address",
    accessStatusTable: "Access Status",
    assignedRoleTable: "Assigned Role",
    actionPanelTable: "Approve / Reject Action Panel",
    approve: "Approve",
    reject: "Reject",
    makeAdmin: "Make Admin",
    revokeAdmin: "Revoke Admin",
    // Admin Product Catalog
    variantsAndRecipesDesc: "Fine-tune variant sizes and bake ingredient formulas (flour, water, starter, salt) in grams.",
    createNewProduct: "Create New Product",
    editProductTitle: "Edit Product & Size Ratios",
    createArtisanProductTitle: "Create Artisan Product",
    productNameLabel: "Product Name",
    descriptionLabel: "Description",
    bakersPercentageTitle: "Baker's Percentage Formula Creator",
    bakersPercentageDesc: "Auto-calculate water, starter, and salt based on flour weights.",
    hydrationLabel: "Hydration (Water) %",
    starterLeavenLabel: "Starter / Leaven %",
    fineSaltLabel: "Fine Salt %",
    formulaScaledExtras: "Formula-scaled Extras (e.g. Cheddar, Rosemary, Olives)",
    addCustomFormulaExtra: "Add Custom Formula Extra",
    noFormulaScaledExtras: "No formula-scaled extra ingredients defined yet.",
    ingredientPlaceholder: "Ingredient (e.g. Cheddar)",
    sizeVariantsAndRecipes: "Size Variants & Baked Recipes",
    addVariantSize: "Add Variant Size",
    sizeNameLabel: "Size Name",
    priceLabel: "Price ($)",
    flourLabel: "Flour (g)",
    waterLabel: "Water (g)",
    starterLabel: "Starter (g)",
    saltLabel: "Salt (g)",
    flourBreakdownTitle: "Flour Breakdown (Percentages must sum to exactly 100%)",
    addFlourType: "Add Flour Type",
    noFlourBreakdown: "No custom flour breakdown set (defaults to 100% Bread Flour).",
    totalRatio: "Total Ratio:",
    enrichmentsFillingsExtras: "Enrichments, Fillings & Extras",
    addExtraIngredient: "Add Extra Ingredient",
    noExtrasFormula: "No formula-scaled extra ingredients are set in the Formula Creator above.",
    noExtrasManual: "No custom extra ingredients set for this variant size.",
    saveProductDetails: "Save Product details",
    recipesPerVariant: "Recipes per size variant",
    flourText: "Flour",
    waterText: "Water",
    starterText: "Starter",
    saltText: "Salt",
    floursText: "Flours",
    extrasText: "Extras",
    recipeUndefined: "Recipe is undefined!",
    // Admin Weekly Menu
    weeklyMenuPublisher: "Weekly Menu Publisher",
    weeklyMenuPublisherDesc: "Activate or deactivate products available for the upcoming baking cycle.",
    selectProductsMonday: "Select Products for the upcoming Monday Cycle",
    // Admin Baking Orders
    customerBakingOrders: "Customer Baking Orders",
    customerBakingOrdersDesc: "Track incoming requests, update baking statuses, or group them into locked production runs.",
    batchCompiler: "Batch Compiler",
    compileLockedBatch: "Compile locked Batch",
    batchCheckbox: "Batch?",
    orderIdDate: "Order ID & Date",
    customer: "Customer",
    itemsBreakdown: "Items Breakdown",
    ovenStatus: "Oven Status",
    ovenControls: "Oven Controls",
    batched: "Batched",
    // Admin Production Batches
    relationalProductionRuns: "Relational Production Runs",
    relationalProductionRunsDesc: "Lock generated batches, preview ingredient scales, or load ESC-POS thermal rolls.",
    bakeDate: "Bake Date:",
    batchUid: "Batch UID:",
    locked: "Locked",
    draft: "Draft",
    ordersLinked: "Orders Linked:",
    estLoavesCount: "Estimated Loaves Count:",
    lockRun: "Lock Run",
    unlock: "Unlock",
    loadLabels: "Load Labels",
    labelPrintShop: "Label Print Shop",
    labelPrintShopDesc: "HTML and ESC-POS simulated fallbacks for 80mm thermal roll sticker printing.",
    backToBatches: "Back to batches",
    printAllStickers: "Print all stickers ({count})",
    thermalConfig: "Thermal Configuration",
    thermalConfigDesc: "We render standard 80mm roll dimensions. Clicking Print All triggers standard browser print media directives which suppress headers, footers, background graphics, and isolate labels with automatic sticker breaks!",
    bakingDateLabel: "Baking Date:",
    clientLabel: "Client:",
    bakedLabel: "Baked:",
    sizeLabel: "Size:",
    weeklyRecurringLoaves: "Weekly recurring loaves",
    weeklySubValue: "Weekly Subscription Value",
    estWeeklyMrrContribution: "Estimated weekly MRR contribution",
    totalSubscribers: "Total Subscribers",
    loyalLocalFamilies: "Loyal local families",
    itemSubscribed: "Item Subscribed",
    qtyAndSlot: "Quantity & Slot",
    weeklyPrice: "Weekly Price",
    actionsTable: "Actions",
    noStandingOrdersYet: "No standing orders registered yet. Customers can select 'Save as repeating weekly order' during checkout.",
    qty: "Qty",
    slotLabel: "Slot:",
    inactive: "Inactive",
    pauseButton: "Pause",
    activateButton: "Activate",
    cancelSubscriptionConfirm: "Are you sure you want to cancel this weekly subscription?",
    standingOrderStatusUpdated: "Standing order status updated.",
    standingOrderCancelled: "Standing order cancelled.",
    // Admin Standing Subscriptions
    activeSubscriptionsTitle: "Weekly Standing Subscriptions Generator",
    activeSubscriptionsDesc: "Process customer recurring bakes, calculate MRR, and auto-generate normal pending orders.",
    generateWeeklyOrders: "Generate Weekly Orders",
    standingOrderPanel: "Standing Order Panel",
    mrrEst: "Est. Monthly Revenue (MRR)",
    activeSubsCount: "Active Subscriptions",
    totalItemsCount: "Total Recurring Items",
    customerPhone: "Customer & Phone",
    recurringItems: "Recurring Items",
    pickupSchedule: "Pickup Schedule",
    subscriptionStatus: "Subscription Status",
    createdOn: "Created On",
    active: "Active",
    paused: "Paused",
    // Customer Dashboard
    weeklyMenu: "Weekly Menu",
    myOrders: "My Orders",
    mySubscriptionsProfile: "Subscriptions & Profile",
    shoppingCart: "Shopping Cart",
    cartEmpty: "Your basket is empty. Select fresh sourdough loaves from the menu!",
    checkoutDetails: "Checkout Collection Details",
    collectionTimeSlot: "Select Collection Time Slot",
    saveAsStanding: "Save as my repeating Weekly Standing Order (Subscription)",
    lockOrderSubmit: "Lock in Order",
    totalAmount: "Total Amount:",
    addBasket: "Add to Basket",
    noProductsActive: "No products are currently active in this week's menu. Check back soon!",
    bakingStatusProgress: "Baking Progress Status",
    orderHash: "Order",
    orderedOn: "Ordered On",
    collectionSlot: "Collection Slot",
    itemsOrdered: "Items Ordered",
    recurringWeeklySubscription: "Recurring Weekly Subscription",
    noOrdersPlaced: "You haven't placed any bakes yet. Browse our weekly menu!",
    myProfileDetails: "My Profile Details",
    fullLegalName: "Full Legal Name",
    phoneContact: "WhatsApp Phone Number (e.g. +33612345678)",
    saveProfileDetails: "Save Profile Details",
    activeSubscriptionsCustomer: "Your Active Weekly Subscriptions",
    recurringWeeklyItems: "Recurring Weekly Items",
    registeredOn: "Registered On",
    noActiveSubsCustomer: "You don't have any active subscriptions. Select \"Save as Standing Order\" at checkout to subscribe!",
    // Missing Customer Dashboard & Feedback Keys
    profileUpdatedSuccess: "Profile updated successfully!",
    profileUpdatedFailed: "Failed to update profile",
    profileUpdateError: "Could not connect to update profile.",
    orderAndSubLockedIn: "Order & Weekly Subscription locked in! Welcome to our regular club.",
    orderSubmittedSuccess: "Order submitted successfully! Our bakers are getting ready.",
    orderSubmitFailed: "Failed to submit order",
    orderSubmitError: "Could not connect to the baking engine. Try again.",
    artisanMicrobakery: "Artisan Microbakery",
    approved: "Approved",
    bakingNextMonday: "Baking next: Monday Morning",
    bakedFreshOnDemand: "Baked Fresh on Demand",
    menuNotPublished: "The bakers haven't published this week's menu yet.",
    checkBackSoonLoaves: "Check back soon for freshly rolled loaves!",
    availableSizes: "Available Sizes",
    myBakingBasket: "My Baking Basket",
    cartEmptyDesc: "Add variants from the menu on the left to start building your bake order.",
    saveAsStandingOrderDesc: "Save as my repeating Weekly Standing Order! We will auto-book this for you every week if these items are active.",
    itemsCount: "Items Count",
    lockInAndSubscribe: "Lock In & Subscribe",
    orderStatusHistory: "Order Status & History",
    noOrdersPlacedDesc: "Once you request bread, progress will be live-tracked here!",
    bakingBatch: "Baking Batch",
    queuedAwaitingBatching: "Queued (Awaiting Batching)",
    pendingStatus: "Pending",
    confirmedStatus: "Confirmed",
    inOvenStatus: "In Oven",
    readyStatus: "Ready",
    orderDetailsCount: "Order Details ({count} items)",
    phoneContactDesc: "Enables the baker to ping you directly on WhatsApp when your loaf is fresh in the oven!",
    // WhatsApp Helper Modal Keys
    whatsappHelperTitle: "WhatsApp Notification Helper",
    orderIdLabel: "Order ID: {id}",
    noPhoneConfigured: "⚠️ No phone number configured for this customer.",
    selectScriptTemplate: "Select Script Template",
    orderConfirmedTemplate: "Order Confirmed",
    bakingNowTemplate: "Baking Now",
    readyForPickupTemplate: "Ready for Pickup",
    editPrefilledMessage: "Edit Pre-filled Text Message",
    sendToWhatsapp: "Send to WhatsApp",
    // WhatsApp Messages Template Keys
    whatsappConfirmedMessage: "Hi {name}! 🍞 Your order #{id} at La Petite Farine has been confirmed. We're preparing your fresh artisanal bakes ({items}) for your selected slot: {slot}! See you soon!",
    whatsappBakingMessage: "Hi {name}! 🔥 Just to let you know, your bread is in the oven right now at La Petite Farine! The bakery smells amazing, and your bakes ({items}) will be ready for pickup during your slot: {slot}.",
    whatsappReadyMessage: "Hi {name}! 🎉 Exciting news - your fresh bakes ({items}) are ready! 🥖 Warm, crusty, and waiting for you to pick them up during your slot: {slot}. See you at La Petite Farine!",
    whatsappGroupedConfirmedMessage: "Hi {name}! 🍞 Your order at La Petite Farine for {date} is confirmed! We are preparing your fresh artisanal bakes ({items}) for slot: {slot}! See you soon!",
    whatsappGroupedBakingMessage: "Hi {name}! 🔥 Just to let you know, we are in the process of mixing & baking your fresh artisanal bakes ({items}) today! Everything is smelling amazing at La Petite Farine, and they will be ready for pickup during slot: {slot}.",
    whatsappGroupedReadyMessage: "Hi {name}! 🎉 Exciting news - your fresh bakes ({items}) are completed and ready for pickup! 🥖 Warm, crusty, and waiting for you during your slot: {slot}. See you at La Petite Farine!",
    addInternalOrderBtn: "Add Internal Order",
    addInternalOrderTitle: "Add New Internal / Guest Order",
    customerInfo: "Customer Details",
    guestName: "Guest Name / Nickname",
    guestPhone: "Phone Number (Optional - for WhatsApp)",
    guestEmail: "Email Address (Optional)",
    itemsAndQuantities: "Items & Quantities",
    selectProductVariant: "Select Product & Size...",
    addAnotherItem: "＋ Add Another Product",
    submitOrder: "Submit Order",
    internalOrderSuccess: "Internal order added successfully!",
    internalOrderFailed: "Failed to submit internal order. Check details.",
    settings: "Settings",
    bakingDaysConfig: "Baking Days Configuration",
    bakingDaysDesc: "Select which days of the week you bake. Customers will see upcoming dates for these days during checkout.",
    searchPlaceholder: "Search orders by customer name or phone...",
    settingsSaved: "Settings saved successfully!",
    changeBakingDay: "Change Baking Day",
    selectNewDate: "Select New Baking Date",
    saveChanges: "Save Changes",
    leadTimeHoursLabel: "Order Cut-off Lead Time",
    leadTimeHoursDesc: "Set how many hours before the bake day a customer can place an order. If set to 72 hours (3 days), a Tuesday morning bake will cut off on Saturday morning.",
    hoursLabel: "{hours} hours",
    lastCallDeadlines: "Backtracking Helper: Last Call Deadlines",
    lastCallDeadlinesDesc: "Calculated cut-off deadlines for each active baking day based on the configured hours (assuming baking starts at 06:00 AM of that day):",
    bakingDay: "Baking Day",
    lastCallDeadline: "Last Call Deadline",
    loyaltyTracker: "Loyalty Rewards",
    loyaltyTrackerDesc: "Monitor user purchase milestones and reward redemptions. For every 10 items purchased in COMPLETED orders, the customer earns 1 free loaf.",
    loyaltyRewardsTitle: "🏆 Sourdough Loyalty Card",
    loyaltyProgress: "Loyalty Progress",
    totalBought: "Total Bought",
    freeEarned: "Free Earned",
    freeRedeemed: "Redeemed",
    freeRemaining: "Remaining",
    stampsRemaining: "{stamps} stamps to your next free loaf!",
    stampCardSubtitle: "For every 10 sourdough loaves you buy, the next 1 is on us!",
    claimInstruction: "Show this screen to the baker to redeem your free loaf!",
    redeemLoaf: "Redeem Free Loaf",
    redeemLoafSuccess: "Successfully redeemed 1 free loaf!",
    redeemLoafError: "Cannot redeem: no remaining free loaves.",
    customerLedger: "My Bread Ledger",
    customerLedgerDesc: "A record of your completed purchases:",
    dateLabel: "Date",
    productLabel: "Product",
    quantityLabel: "Qty",
    itemLabel: "Item",
    userLoyaltyProgress: "User Loyalty Progress",
    loyaltyActionRedeem: "Mark 1 Loaf as Redeemed",
    viewHistory: "View History",
    searchByClient: "Search by customer name, phone, or email...",
    freeLoafCount: "Free loaf",
    freeLoavesCount: "Free loaves",
    remainingLabel: "Remaining",
    couponsAvailableTitle: "🎁 Available Loyalty Coupons",
    couponsAvailableDesc: "You have {count} free loaf coupon(s) ready to redeem! Apply them inline on your basket items below.",
    applyCouponBtn: "🎁 Use Coupon",
    appliedCouponPill: "🎁 Coupon Applied",
    couponDiscounted: "Coupon Discounted",
    freeLoafBadge: "🎁 FREE LOAF",
    discountedText: "Discounted"
  },
  hr: {
    // Auth & Common
    laminatingDough: "Laminiranje tijesta",
    monday: "Ponedjeljak",
    tuesday: "Utorak",
    wednesday: "Srijeda",
    thursday: "Četvrtak",
    friday: "Petak",
    saturday: "Subota",
    sunday: "Nedjelja",
    activeSubscriptionsCustomerDesc: "Vaše aktivne ponavljajuće tjedne narudžbe. Naši pekari automatski pripremaju ove proizvode u svakom ciklusu!",
    connectingOven: "Povezivanje s jezgrom pećnice...",
    laPetiteFarine: "La Petite Farine",
    microbakeryMgmt: "Sustav upravljanja mikro-pekarnicom",
    emailAddr: "E-mail adresa",
    password: "Lozinka",
    fullName: "Puno ime",
    registerAccount: "Registriraj račun",
    authenticateSession: "Prijavi se",
    signInWithGoogle: "Prijavi se Google-om",
    registerWithGoogle: "Registriraj se Google-om",
    alreadyRegistered: "Već imate račun? Prijavite se ovdje",
    newBakeryClient: "Novi klijent? Izradite račun ovdje",
    awaitingApproval: "Čeka se odobrenje pekara",
    awaitingApprovalDesc: "Dobrodošli u La Petite Farine, {name}! Vaša registracija je trenutno u redu čekanja. Kako bismo zaštitili precizno planiranje proizvodnje, naš pekar ručno odobrava pristup kupcima.",
    assignedStatus: "Dodijeljeni status",
    checkStatusAgain: "Provjeri status ponovno",
    accessRestricted: "Pristup ograničen",
    accessRestrictedDesc: "Nažalost, vaša registracija je odbijena. Ako smatrate da je ovo pogreška, obratite se izravno upravi pekarnice.",
    logout: "Odjava",
    cancel: "Odustani",
    save: "Spremi",
    edit: "Uredi",
    delete: "Ukloni",
    statusText: "Status",
    // Admin Sidebar
    adminCore: "Upravljanje mikro-pekarnicom",
    overview: "Pregled",
    userApprovals: "Odobrenja korisnika",
    productRecipes: "Proizvodi i recepti",
    weeklyMenuPlanner: "Planer tjednog menija",
    bakingOrders: "Narudžbe za pečenje",
    productionBatches: "Proizvodne serije",
    standingSubscriptions: "Stalne pretplate",
    bakeryOwner: "Vlasnik pekarnice",
    // Admin Overview
    bakeryDashboard: "Nadzorna ploča",
    realtimeOps: "Praćenje proizvodnje i potreba za brašnom u stvarnom vremenu",
    refreshEngine: "Osvježi podatke",
    totalActiveOrders: "Ukupno aktivnih narudžbi",
    totalProductsBaking: "Ukupno proizvoda za pečenje",
    ordersLabel: "narudžbe",
    itemsLabel: "artikli",
    cumulFlourKg: "Ukupno brašna",
    totalEstDoughWeight: "Procjena težine tijesta",
    readyForOven: "Spremno za pećnicu",
    unapprovedSignups: "Neodobreni korisnici",
    awaitingApprovalLabel: "Čeka odobrenje",
    productsCatalog: "Katalog proizvoda",
    activeCategories: "Aktivni proizvodi",
    weeklyBatches: "Tjedne serije",
    lockedProductionRuns: "Zaključane serije",
    autoIngredientCalc: "Automatski izračun sastojaka",
    dynamicSummary: "Dinamički sažetak",
    allActiveOrders: "Sve aktivne narudžbe (Nedovršene)",
    filterByBatch: "Filtriraj po seriji",
    flourRequired: "Potrebno brašno",
    waterRequired: "Potrebna voda",
    starterLeaven: "Kvas / Kvasac (Starter)",
    fineSeaSalt: "Sitna morska sol",
    flourTypesBreakdown: "Raščlamba vrsta brašna",
    richEnrichment: "Bogati dodaci, punjenja i extras",
    missingFormulas: "Nedostaju recepti za:",
    missingFormulasDesc: "Sastojci za {recipes} ne mogu se u potpunosti izračunati jer recepti za varijante nisu definirani. Idite na karticu Proizvodi i unesite recepte.",
    estCumulativeDough: "Ukupna procijenjena masa tijesta:",
    bakeListBreakdown: "Količine za pečenje",
    noActiveCalculations: "Nema aktivnih izračuna. Dodajte potvrđene narudžbe.",
    noBakingBreakdowns: "Nema planiranog pečenja za ovaj tjedan.",
    // Bulk mixing container card
    bulkMixingTitle: "🥣 Skupno miješanje u jednoj posudi (Serije)",
    bulkMixingDesc: "Grupirajte različite veličine istog recepta u jednu veliku posudu za skupnu fermentaciju i lakše porcioniranje.",
    totalFlour: "Ukupno brašno",
    totalWater: "Ukupna voda",
    totalStarter: "Ukupno starter (kvasac)",
    totalSalt: "Ukupno morska sol",
    totalBatchWeight: "Ukupna masa miješane serije",
    scalingInstructions: "⚖️ Upute za porcioniranje i rezanje",
    scalingInstructionsDesc: "Nakon završetka fermentacije, podijelite tijesto iz ove posude na sljedeće porcije:",
    portionSize: "Portionirajte {qty}x {size} štruce: Odrežite komad mase {weight}g",
    orGramsFlour: "(baza od {flour}g brašna po štruci)",
    noBulkMixing: "Trenutno nema skupnih serija za miješanje. Prvo dodajte aktivne narudžbe.",
    // Admin User Approvals
    customerRegApprovals: "Odobrenja registracije kupaca",
    customerRegApprovalsDesc: "Samo odobreni kupci mogu pristupiti tjednim menijima i naručiti kruh.",
    customerName: "Ime kupca",
    emailAddressTable: "E-mail adresa",
    accessStatusTable: "Status pristupa",
    assignedRoleTable: "Uloga",
    actionPanelTable: "Upravljanje pristupom (Odobri / Odbij)",
    approve: "Odobri",
    reject: "Odbij",
    makeAdmin: "Učini adminom",
    revokeAdmin: "Ukloni admina",
    // Admin Product Catalog
    variantsAndRecipesDesc: "Prilagodite veličine varijanti i recepte sastojaka (brašno, voda, starter, sol) u gramima.",
    createNewProduct: "Dodaj novi proizvod",
    editProductTitle: "Uredi proizvod i omjere",
    createArtisanProductTitle: "Izradi zanatski proizvod",
    productNameLabel: "Naziv proizvoda",
    descriptionLabel: "Opis",
    bakersPercentageTitle: "Kalkulator pekarskih postotaka",
    bakersPercentageDesc: "Automatski izračunaj vodu, starter i sol na temelju težine brašna.",
    hydrationLabel: "Hidratacija (Voda) %",
    starterLeavenLabel: "Kvas / Starter %",
    fineSaltLabel: "Sol %",
    formulaScaledExtras: "Dodaci skalirani formulom (npr. Cheddar, Ružmarin, Masline)",
    addCustomFormulaExtra: "Dodaj dodatak u formulu",
    noFormulaScaledExtras: "Još nema dodataka skaliranih formulom.",
    ingredientPlaceholder: "Sastojak (npr. Cheddar)",
    sizeVariantsAndRecipes: "Veličine varijanti i recepti",
    addVariantSize: "Dodaj veličinu varijante",
    sizeNameLabel: "Naziv veličine",
    priceLabel: "Cijena ($)",
    flourLabel: "Brašno (g)",
    waterLabel: "Voda (g)",
    starterLabel: "Starter (g)",
    saltLabel: "Sol (g)",
    flourBreakdownTitle: "Omjeri brašna (Zbroj postotaka mora biti točno 100%)",
    addFlourType: "Dodaj vrstu brašna",
    noFlourBreakdown: "Nema posebnih vrsta brašna (koristi se 100% bijelo pšenično brašno).",
    totalRatio: "Ukupni omjer:",
    enrichmentsFillingsExtras: "Obogaćenja, punjenja i dodaci",
    addExtraIngredient: "Dodaj dodatak ručno",
    noExtrasFormula: "Nema dodataka skaliranih formulom postavljenog iznad.",
    noExtrasManual: "Nema ručnih dodataka za ovu varijantu.",
    saveProductDetails: "Spremi detalje proizvoda",
    recipesPerVariant: "Recepti po varijantama veličina",
    flourText: "Brašno",
    waterText: "Voda",
    starterText: "Starter",
    saltText: "Sol",
    floursText: "Brašna",
    extrasText: "Dodaci",
    recipeUndefined: "Recept nije definiran!",
    // Admin Weekly Menu
    weeklyMenuPublisher: "Upravljanje tjednim menijem",
    weeklyMenuPublisherDesc: "Aktivirajte ili deaktivirajte proizvode dostupne za nadolazeći ciklus pečenja.",
    selectProductsMonday: "Odaberite proizvode za nadolazeći ponedjeljak",
    // Admin Baking Orders
    customerBakingOrders: "Narudžbe kupaca",
    customerBakingOrdersDesc: "Pratite pristigle zahtjeve, ažurirajte statuse pečenja ili ih grupirajte u proizvodne serije.",
    batchCompiler: "Sastavljač proizvodne serije",
    compileLockedBatch: "Sastavi zaključanu seriju",
    batchCheckbox: "Serija?",
    orderIdDate: "ID narudžbe i datum",
    customer: "Kupac",
    itemsBreakdown: "Stavke narudžbe",
    ovenStatus: "Status pečenja",
    ovenControls: "Kontrole statusa",
    batched: "Grupirano",
    // Admin Production Batches
    relationalProductionRuns: "Proizvodne serije",
    relationalProductionRunsDesc: "Zaključajte serije, pregledajte raspodjelu sastojaka ili generirajte etikete za tisak.",
    bakeDate: "Datum pečenja:",
    batchUid: "UID serije:",
    locked: "Zaključano",
    draft: "Skica",
    ordersLinked: "Povezane narudžbe:",
    estLoavesCount: "Procijenjeni broj štruca:",
    lockRun: "Zaključaj seriju",
    unlock: "Otključaj",
    loadLabels: "Generiraj etikete",
    labelPrintShop: "Tiskara etiketa",
    labelPrintShopDesc: "HTML i ESC-POS simulacija ispisa 80 mm termalnih naljepnica.",
    backToBatches: "Povratak na serije",
    printAllStickers: "Ispiši sve naljepnice ({count})",
    thermalConfig: "Termalne postavke",
    thermalConfigDesc: "Prikazujemo standardne dimenzije od 80 mm. Klikom na 'Ispiši sve' pokreću se standardne print media direktive koje uklanjaju zaglavlja, podnožja i izoliraju etikete s automatskim prekidima!",
    bakingDateLabel: "Datum pečenja:",
    clientLabel: "Kupac:",
    bakedLabel: "Pečeno:",
    sizeLabel: "Veličina:",
    weeklyRecurringLoaves: "Tjedni ponavljajući kruhovi",
    weeklySubValue: "Vrijednost tjedne pretplate",
    estWeeklyMrrContribution: "Procijenjeni tjedni doprinos MRR-u",
    totalSubscribers: "Ukupno pretplatnika",
    loyalLocalFamilies: "Vjerne lokalne obitelji",
    itemSubscribed: "Pretplatni artikl",
    qtyAndSlot: "Količina i termin",
    weeklyPrice: "Tjedna cijena",
    actionsTable: "Akcije",
    noStandingOrdersYet: "Još nema registriranih stalnih narudžbi. Kupci mogu odabrati 'Spremi kao tjednu pretplatu' prilikom plaćanja.",
    qty: "Kol",
    slotLabel: "Termin:",
    inactive: "Neaktivno",
    pauseButton: "Pauziraj",
    activateButton: "Aktiviraj",
    cancelSubscriptionConfirm: "Jeste li sigurni da želite otkazati ovu tjednu pretplatu?",
    standingOrderStatusUpdated: "Status stalne narudžbe je ažuriran.",
    standingOrderCancelled: "Stalna narudžba je otkazana.",
    // Admin Standing Subscriptions
    activeSubscriptionsTitle: "Upravljanje tjednim pretplatama (Stalne narudžbe)",
    activeSubscriptionsDesc: "Obradite ponavljajuće narudžbe, izračunajte mjesečne prihode (MRR) i automatski generirajte tjedne narudžbe.",
    generateWeeklyOrders: "Generiraj tjedne narudžbe",
    standingOrderPanel: "Pretplate",
    mrrEst: "Procjena mjesečnih prihoda (MRR)",
    activeSubsCount: "Aktivne pretplate",
    totalItemsCount: "Ukupno ponavljajućih stavki",
    customerPhone: "Kupac i telefon",
    recurringItems: "Ponavljajuće stavke",
    pickupSchedule: "Raspored preuzimanja",
    subscriptionStatus: "Status pretplate",
    createdOn: "Izrađeno dana",
    active: "Aktivno",
    paused: "Pauzirano",
    // Customer Dashboard
    weeklyMenu: "Tjedni meni",
    myOrders: "Moje narudžbe",
    mySubscriptionsProfile: "Pretplate i profil",
    shoppingCart: "Košarica",
    cartEmpty: "Vaša košarica je prazna. Odaberite svježe proizvode iz tjednog menija!",
    checkoutDetails: "Detalji preuzimanja narudžbe",
    collectionTimeSlot: "Odaberite termin preuzimanja",
    saveAsStanding: "Spremi kao tjednu pretplatu (Stalna narudžba)",
    lockOrderSubmit: "Pošalji narudžbu",
    totalAmount: "Ukupni iznos:",
    addBasket: "Dodaj u košaricu",
    noProductsActive: "Trenutno nema aktivnih proizvoda na tjednom meniju. Navratite uskoro!",
    bakingStatusProgress: "Napredak pečenja",
    orderHash: "Narudžba",
    orderedOn: "Naručeno dana",
    collectionSlot: "Termin preuzimanja",
    itemsOrdered: "Naručene stavke",
    recurringWeeklySubscription: "Tjedna pretplata",
    noOrdersPlaced: "Još niste izvršili nijednu narudžbu. Pogledajte naš tjedni meni!",
    myProfileDetails: "Moj profil",
    fullLegalName: "Puno ime i prezime",
    phoneContact: "WhatsApp broj telefona (npr. +38591234567)",
    saveProfileDetails: "Spremi izmjene profila",
    activeSubscriptionsCustomer: "Vaše aktivne tjedne pretplate",
    recurringWeeklyItems: "Ponavljajući tjedni proizvodi",
    registeredOn: "Registrirano dana",
    noActiveSubsCustomer: "Nemate aktivnih pretplata. Odaberite \"Spremi kao tjednu pretplatu\" prilikom slanja narudžbe!",
    // Missing Customer Dashboard & Feedback Keys
    profileUpdatedSuccess: "Profil uspješno ažuriran!",
    profileUpdatedFailed: "Ažuriranje profila nije uspjelo",
    profileUpdateError: "Nije se moguće povezati za ažuriranje profila.",
    orderAndSubLockedIn: "Narudžba i tjedna pretplata su zaključane! Dobrodošli u naš klub redovitih kupaca.",
    orderSubmittedSuccess: "Narudžba uspješno poslana! Naši pekari se pripremaju.",
    orderSubmitFailed: "Slanje narudžbe nije uspjelo",
    orderSubmitError: "Nije se moguće povezati sa sustavom pečenja. Pokušajte ponovno.",
    artisanMicrobakery: "Zanatska mikro-pekarnica",
    approved: "Odobreno",
    bakingNextMonday: "Sljedeće pečenje: ponedjeljak ujutro",
    bakedFreshOnDemand: "Pečeno svježe na zahtjev",
    menuNotPublished: "Pekari još nisu objavili tjedni meni.",
    checkBackSoonLoaves: "Navratite uskoro po svježe štruce!",
    availableSizes: "Dostupne veličine",
    myBakingBasket: "Moja košarica za pečenje",
    cartEmptyDesc: "Dodajte varijante iz menija s lijeve strane kako biste sastavili narudžbu.",
    saveAsStandingOrderDesc: "Spremi kao ponavljajući tjedni nalog! Automatski ćemo ovo rezervirati za vas svaki tjedan ako su artikli aktivni.",
    itemsCount: "Broj artikala",
    lockInAndSubscribe: "Zaključaj i pretplati se",
    orderStatusHistory: "Status i povijest narudžbi",
    noOrdersPlacedDesc: "Nakon što naručite kruh, napredak će se pratiti ovdje uživo!",
    bakingBatch: "Serija pečenja",
    queuedAwaitingBatching: "U redu čekanja (Čeka grupiranje)",
    pendingStatus: "U tijeku",
    confirmedStatus: "Potvrđeno",
    inOvenStatus: "U pećnici",
    readyStatus: "Spremno",
    orderDetailsCount: "Detalji narudžbe ({count} kom)",
    phoneContactDesc: "Omogućuje pekaru da vas izravno kontaktira na WhatsApp kada vam je kruh svjež u pećnici!",
    // WhatsApp Helper Modal Keys
    whatsappHelperTitle: "WhatsApp pomoćnik za obavijesti",
    orderIdLabel: "ID narudžbe: {id}",
    noPhoneConfigured: "⚠️ Korisnik nema konfiguriran broj telefona.",
    selectScriptTemplate: "Odaberite predložak poruke",
    orderConfirmedTemplate: "Narudžba potvrđena",
    bakingNowTemplate: "Peče se sada",
    readyForPickupTemplate: "Spremno za preuzimanje",
    editPrefilledMessage: "Uredi tekst poruke",
    sendToWhatsapp: "Pošalji na WhatsApp",
    // WhatsApp Messages Template Keys
    whatsappConfirmedMessage: "Bok {name}! 🍞 Primili smo tvoju narudžbu #{id} i sve je potvrđeno. Pripremamo ti {items} za termin {slot}. Vidimo se! 🥖",
    whatsappBakingMessage: "Bok {name}! 🔥 Samo javljam da se tvoj kruh ({items}) upravo peče i miriše super! Čeka te u terminu {slot}. Vidimo se uskoro! 🥐",
    whatsappReadyMessage: "Bok {name}! 🎉 Tvoja narudžba ({items}) je gotova, topla i hrskava! Čeka te za preuzimanje u terminu {slot}. Vidimo se! 🥖✨",
    whatsappGroupedConfirmedMessage: "Bok {name}! 🍞 Primili smo tvoje narudžbe za {date} i sve je potvrđeno. Pripremamo ti {items} za termin {slot}. Vidimo se! 🥖",
    whatsappGroupedBakingMessage: "Bok {name}! 🔥 Samo javljam da se tvoj kruh ({items}) upravo peče i miriše super! Čeka te u terminu {slot}. Vidimo se uskoro! 🥐",
    whatsappGroupedReadyMessage: "Bok {name}! 🎉 Tvoja narudžba ({items}) je gotova, topla i hrskava! Čeka te za preuzimanje u terminu {slot}. Vidimo se! 🥖✨",
    addInternalOrderBtn: "Dodaj internu narudžbu",
    addInternalOrderTitle: "Dodaj novu internu / gostujuću narudžbu",
    customerInfo: "Podaci o kupcu",
    guestName: "Ime gosta / Nadimak",
    guestPhone: "Broj mobitela (Opcionalno - za WhatsApp)",
    guestEmail: "E-mail adresa (Opcionalno)",
    itemsAndQuantities: "Proizvodi i količine",
    selectProductVariant: "Odaberite proizvod i veličinu...",
    addAnotherItem: "＋ Dodaj još jedan proizvod",
    submitOrder: "Pošalji narudžbu",
    internalOrderSuccess: "Interna narudžba uspješno dodana!",
    internalOrderFailed: "Neuspjelo slanje interne narudžbe. Provjerite podatke.",
    settings: "Postavke",
    bakingDaysConfig: "Konfiguracija dana pečenja",
    bakingDaysDesc: "Odaberite kojim danima u tjednu pečete. Kupci će vidjeti nadolazeće datume za ove dane prilikom plaćanja.",
    searchPlaceholder: "Pretraži narudžbe po imenu kupca ili broju...",
    settingsSaved: "Postavke uspješno spremljene!",
    changeBakingDay: "Promijeni dan pečenja",
    selectNewDate: "Odaberite novi datum pečenja",
    saveChanges: "Spremi promjene",
    leadTimeHoursLabel: "Vrijeme zatvaranja narudžbi",
    leadTimeHoursDesc: "Postavite koliko sati prije dana pečenja kupac može poslati narudžbu. Ako je postavljeno na 72 sata (3 dana), narudžbe za utorak ujutro zatvaraju se u subotu ujutro.",
    hoursLabel: "{hours} sati",
    lastCallDeadlines: "Pomoćnik za izračun: Rokovi zadnjeg poziva",
    lastCallDeadlinesDesc: "Izračunati rokovi za svaki aktivni dan pečenja na temelju konfiguriranih sati (uz pretpostavku da pečenje počinje u 06:00 ujutro tog dana):",
    bakingDay: "Dan pečenja",
    lastCallDeadline: "Rok zadnjeg poziva",
    loyaltyTracker: "Program vjernosti",
    loyaltyTrackerDesc: "Pratite prekretnice kupnje korisnika i iskorištavanje nagrada. Za svakih 10 kupljenih proizvoda u DOVRŠENIM narudžbama, kupac dobiva 1 besplatni kruh.",
    loyaltyRewardsTitle: "🏆 Kartica vjernosti za sourdough",
    loyaltyProgress: "Napredak vjernosti",
    totalBought: "Ukupno kupljeno",
    freeEarned: "Besplatno zarađeno",
    freeRedeemed: "Iskorišteno",
    freeRemaining: "Preostalo",
    stampsRemaining: "Još {stamps} pečata do vašeg sljedećeg besplatnog kruha!",
    stampCardSubtitle: "Za svakih 10 kupljenih sourdough kruhova, sljedeći je na naš račun!",
    claimInstruction: "Pokažite ovaj ekran pekaru kako biste preuzeli svoj besplatni kruh!",
    redeemLoaf: "Iskoristi besplatni kruh",
    redeemLoafSuccess: "Uspješno iskorišten 1 besplatni kruh!",
    redeemLoafError: "Nije moguće iskoristiti: nema preostalih besplatnih kruhova.",
    customerLedger: "Moja knjiga kruha",
    customerLedgerDesc: "Povijest vaših dovršenih kupnji:",
    dateLabel: "Datum",
    productLabel: "Proizvod",
    quantityLabel: "Kol",
    itemLabel: "Artikl",
    userLoyaltyProgress: "Korisnički program vjernosti",
    loyaltyActionRedeem: "Onači 1 kruh kao iskorišten",
    viewHistory: "Vidi povijest",
    searchByClient: "Pretraži po imenu kupca, telefonu ili e-pošti...",
    freeLoafCount: "Besplatni kruh",
    freeLoavesCount: "Besplatnih kruhova",
    remainingLabel: "Preostalo",
    couponsAvailableTitle: "🎁 Dostupni kuponi vjernosti",
    couponsAvailableDesc: "Imate {count} kupon(a) za besplatni kruh spremnih za preuzimanje! Primijenite ih ispod na artikle u košarici.",
    applyCouponBtn: "🎁 Iskoristi kupon",
    appliedCouponPill: "🎁 Kupon primijenjen",
    couponDiscounted: "Sniženo kuponom",
    freeLoafBadge: "🎁 BESPLATAN KRUH",
    discountedText: "Sniženo"
  },
  it: {
    // Auth & Common
    laminatingDough: "Laminazione dell'impasto",
    monday: "Lunedì",
    tuesday: "Martedì",
    wednesday: "Mercoledì",
    thursday: "Giovedì",
    friday: "Venerdì",
    saturday: "Sabato",
    sunday: "Domenica",
    activeSubscriptionsCustomerDesc: "I tuoi abbonamenti settimanali ricorrenti attivi. I nostri panettieri preparano automaticamente questi prodotti ad ogni ciclo!",
    connectingOven: "Connessione al cuore del forno artigianale...",
    laPetiteFarine: "La Petite Farine",
    microbakeryMgmt: "Sistema di gestione del micro-panificio",
    emailAddr: "Indirizzo Email",
    password: "Password",
    fullName: "Nome Completo",
    registerAccount: "Registra Account",
    authenticateSession: "Accedi",
    signInWithGoogle: "Accedi con Google",
    registerWithGoogle: "Registrati con Google",
    alreadyRegistered: "Già registrato? Accedi qui",
    newBakeryClient: "Nuovo cliente? Crea un account qui",
    awaitingApproval: "In attesa di approvazione del panettiere",
    awaitingApprovalDesc: "Benvenuto a La Petite Farine, {name}! La tua registrazione è in coda. Per proteggere il bilanciamento dei lotti di produzione, il nostro mastro panettiere approva manualmente l'accesso.",
    assignedStatus: "Stato assegnato",
    checkStatusAgain: "Verifica lo stato di nuovo",
    accessRestricted: "Accesso Limitato",
    accessRestrictedDesc: "Sfortunatamente, la tua registrazione è stata rifiutata. Se ritieni che si tratti di un errore, contatta direttamente l'amministrazione.",
    logout: "Disconnetti",
    cancel: "Annulla",
    save: "Salva",
    edit: "Modifica",
    delete: "Elimina",
    statusText: "Stato",
    // Admin Sidebar
    adminCore: "Micro-panificio Admin",
    overview: "Panoramica",
    userApprovals: "Approvazioni Utenti",
    productRecipes: "Prodotti e Ricette",
    weeklyMenuPlanner: "Pianificatore Menu Settimanale",
    bakingOrders: "Ordini di Cottura",
    productionBatches: "Lotti di Produzione",
    standingSubscriptions: "Abbonamenti Ricorrenti",
    bakeryOwner: "Proprietario del Panificio",
    // Admin Overview
    bakeryDashboard: "Cruscotto Panificio",
    realtimeOps: "Operazioni in tempo reale e requisiti della farina",
    refreshEngine: "Aggiorna Dati",
    totalActiveOrders: "Ordini Attivi Totali",
    totalProductsBaking: "Prodotti in Cottura Totali",
    ordersLabel: "ordini",
    itemsLabel: "articoli",
    cumulFlourKg: "Farina Cumulativa",
    totalEstDoughWeight: "Peso Impasto Stimato",
    readyForOven: "Pronto per il forno",
    unapprovedSignups: "Iscrizioni non approvate",
    awaitingApprovalLabel: "In attesa di approvazione",
    productsCatalog: "Catalogo Prodotti",
    activeCategories: "Prodotti attivi",
    weeklyBatches: "Lotti Settimanali",
    lockedProductionRuns: "Cotture bloccate",
    autoIngredientCalc: "Calcolatore Automatico Ingredienti",
    dynamicSummary: "Riepilogo Dinamico",
    allActiveOrders: "Tutti gli ordini attivi (Non completati)",
    filterByBatch: "Filtra per lotto",
    flourRequired: "Farina Necessaria",
    waterRequired: "Acqua Necessaria",
    starterLeaven: "Lievito Madre / Starter",
    fineSeaSalt: "Sale Marino Fino",
    flourTypesBreakdown: "Ripartizione dei tipi di farina",
    richEnrichment: "Condimenti, Ripieni e Ingredienti Extra",
    missingFormulas: "Ricette mancanti per:",
    missingFormulasDesc: "I calcoli di cottura per {recipes} non possono essere completati perché le ricette delle varianti non sono definite. Vai su Prodotti e specifica le ricette.",
    estCumulativeDough: "Massa totale stimata dell'impasto:",
    bakeListBreakdown: "Dettaglio Cotture",
    noActiveCalculations: "Nessun calcolo attivo. Aggiungi ordini confermati.",
    noBakingBreakdowns: "Nessun dettaglio di cottura pianificato per questa settimana.",
    // Bulk mixing container card
    bulkMixingTitle: "🥣 Impasti di miscelazione a ciotola singola (Lotti)",
    bulkMixingDesc: "Raggruppa diverse dimensioni della stessa ricetta in un unico grande contenitore per la fermentazione di massa e una porzionatura più semplice.",
    totalFlour: "Farina Totale",
    totalWater: "Acqua Totale",
    totalStarter: "Lievito Madre Totale",
    totalSalt: "Sale Marino Totale",
    totalBatchWeight: "Peso Totale dell'Impasto",
    scalingInstructions: "⚖️ Istruzioni per porzionatura e taglio",
    scalingInstructionsDesc: "Una volta completata la fermentazione, dividere l'impasto di questo contenitore nelle seguenti porzioni:",
    portionSize: "Porziona {qty}x {size} pagnotte: Taglia a {weight}g di massa totale",
    orGramsFlour: "(base di farina di {flour}g per pagnotta)",
    noBulkMixing: "Nessun lotto di miscelazione di massa attualmente calcolato. Aggiungi prima ordini attivi.",
    // Admin User Approvals
    customerRegApprovals: "Approvazioni Registrazioni Clienti",
    customerRegApprovalsDesc: "Solo le registrazioni approvate possono accedere ai menu settimanali ed effettuare ordini.",
    customerName: "Nome Cliente",
    emailAddressTable: "Indirizzo Email",
    accessStatusTable: "Stato Accesso",
    assignedRoleTable: "Ruolo",
    actionPanelTable: "Pannello Azioni (Approva / Rifiuta)",
    approve: "Approva",
    reject: "Rifiuta",
    makeAdmin: "Rendi Admin",
    revokeAdmin: "Revoca Admin",
    // Admin Product Catalog
    variantsAndRecipesDesc: "Definisci le dimensioni delle varianti e le ricette degli ingredienti (farina, acqua, lievito, sale) in grammi.",
    createNewProduct: "Crea Nuovo Prodotto",
    editProductTitle: "Modifica Prodotto e Proporzioni",
    createArtisanProductTitle: "Crea Prodotto Artigianale",
    productNameLabel: "Nome Prodotto",
    descriptionLabel: "Descrizione",
    bakersPercentageTitle: "Calcolatore Percentuali del Panificatore",
    bakersPercentageDesc: "Calcola automaticamente acqua, lievito e sale in base al peso della farina.",
    hydrationLabel: "Idratazione (Acqua) %",
    starterLeavenLabel: "Lievito Madre / Starter %",
    fineSaltLabel: "Sale %",
    formulaScaledExtras: "Ingredienti extra proporzionati (es. Cheddar, Rosmarino, Olive)",
    addCustomFormulaExtra: "Aggiungi ingrediente alla formula",
    noFormulaScaledExtras: "Nessun ingrediente extra proporzionato definito.",
    ingredientPlaceholder: "Ingrediente (es. Cheddar)",
    sizeVariantsAndRecipes: "Varianti di Dimensione e Ricette",
    addVariantSize: "Aggiungi Dimensione Variante",
    sizeNameLabel: "Nome Dimensione",
    priceLabel: "Prezzo ($)",
    flourLabel: "Farina (g)",
    waterLabel: "Acqua (g)",
    starterLabel: "Lievito Madre (g)",
    saltLabel: "Sale (g)",
    flourBreakdownTitle: "Ripartizione Farine (La somma delle percentuali deve essere esattamente 100%)",
    addFlourType: "Aggiungi Tipo di Farina",
    noFlourBreakdown: "Nessuna ripartizione farine impostata (impostazione predefinita: 100% farina di grano tenero).",
    totalRatio: "Rapporto Totale:",
    enrichmentsFillingsExtras: "Condimenti, Ripieni e Extra",
    addExtraIngredient: "Aggiungi ingrediente manuale",
    noExtrasFormula: "Nessun ingrediente extra proporzionato impostato sopra.",
    noExtrasManual: "Nessun ingrediente extra manuale impostato per questa variante.",
    saveProductDetails: "Salva dettagli prodotto",
    recipesPerVariant: "Ricette per variante di dimensione",
    flourText: "Farina",
    waterText: "Acqua",
    starterText: "Lievito",
    saltText: "Sale",
    floursText: "Farine",
    extrasText: "Extra",
    recipeUndefined: "La ricetta non è definita!",
    // Admin Weekly Menu
    weeklyMenuPublisher: "Editore Menu Settimanale",
    weeklyMenuPublisherDesc: "Attiva o disattiva i prodotti disponibili per il prossimo ciclo di cottura.",
    selectProductsMonday: "Seleziona i prodotti per il prossimo ciclo di lunedì",
    // Admin Baking Orders
    customerBakingOrders: "Ordini di Cottura Clienti",
    customerBakingOrdersDesc: "Traccia le richieste, aggiorna lo stato delle cotture, o raggruppale in lotti di produzione.",
    batchCompiler: "Compilatore del Lotto",
    compileLockedBatch: "Compila lotto bloccato",
    batchCheckbox: "Lotto?",
    orderIdDate: "ID Ordine e Data",
    customer: "Cliente",
    itemsBreakdown: "Dettaglio Articoli",
    ovenStatus: "Stato Cottura",
    ovenControls: "Controlli Cottura",
    batched: "Raggruppato",
    // Admin Production Batches
    relationalProductionRuns: "Lotti di Produzione",
    relationalProductionRunsDesc: "Blocca i lotti generati, visualizza la scala degli ingredienti o carica le etichette.",
    bakeDate: "Data Cottura:",
    batchUid: "UID Lotto:",
    locked: "Bloccato",
    draft: "Bozza",
    ordersLinked: "Ordini Collegati:",
    estLoavesCount: "Numero di Pagnotte Stimato:",
    lockRun: "Blocca Cottura",
    unlock: "Sblocca",
    loadLabels: "Genera Etichette",
    labelPrintShop: "Centro Stampa Etichette",
    labelPrintShopDesc: "Simulazione HTML ed ESC-POS per la stampa di etichette termiche da 80 mm.",
    backToBatches: "Torna ai lotti",
    printAllStickers: "Stampa tutte le etichette ({count})",
    thermalConfig: "Configurazione termica",
    thermalConfigDesc: "Visualizziamo le dimensioni standard del rotolo da 80 mm. Facendo clic su 'Stampa tutto' si attivano le direttive standard di stampa del browser che nascondono intestazioni, piè di pagina e isolano le etichette!",
    bakingDateLabel: "Data Cottura:",
    clientLabel: "Cliente:",
    bakedLabel: "Cotto il:",
    sizeLabel: "Dimensione:",
    weeklyRecurringLoaves: "Pane ricorrente settimanale",
    weeklySubValue: "Valore Abbonamento Settimanale",
    estWeeklyMrrContribution: "Contributo stimato all'MRR settimanale",
    totalSubscribers: "Abbonati Totali",
    loyalLocalFamilies: "Famiglie locali fedeli",
    itemSubscribed: "Articolo Sottoscritto",
    qtyAndSlot: "Quantità e Fascia",
    weeklyPrice: "Prezzo Settimanale",
    actionsTable: "Azioni",
    noStandingOrdersYet: "Nessun abbonamento registrato. I clienti possono selezionare 'Salva come abbonamento' al pagamento.",
    qty: "Qtà",
    slotLabel: "Fascia:",
    inactive: "Non attivo",
    pauseButton: "Sospendi",
    activateButton: "Attiva",
    cancelSubscriptionConfirm: "Sei sicuro di voler annullare questo abbonamento settimanale?",
    standingOrderStatusUpdated: "Stato dell'abbonamento aggiornato.",
    standingOrderCancelled: "Abbonamento annullato.",
    // Admin Standing Subscriptions
    activeSubscriptionsTitle: "Generatore Abbonamenti Settimanali Ricorrenti",
    activeSubscriptionsDesc: "Elabora gli abbonamenti ricorrenti, calcola l'MRR e genera automaticamente gli ordini normali.",
    generateWeeklyOrders: "Genera Ordini Settimanali",
    standingOrderPanel: "Abbonamenti",
    mrrEst: "Stima dei Ricavi Mensili (MRR)",
    activeSubsCount: "Abbonamenti Attivi",
    totalItemsCount: "Articoli Ricorrenti Totali",
    customerPhone: "Cliente e Telefono",
    recurringItems: "Articoli Ricorrenti",
    pickupSchedule: "Programma di Ritiro",
    subscriptionStatus: "Stato Abbonamento",
    createdOn: "Creato il",
    active: "Attivo",
    paused: "In pausa",
    // Customer Dashboard
    weeklyMenu: "Menu Settimanale",
    myOrders: "I Miei Ordini",
    mySubscriptionsProfile: "Abbonamenti e Profilo",
    shoppingCart: "Carrello",
    cartEmpty: "Il carrello è vuoto. Seleziona pagnotte fresche dal menu!",
    checkoutDetails: "Dettagli Ritiro",
    collectionTimeSlot: "Seleziona la Fascia Oraria di Ritiro",
    saveAsStanding: "Salva come abbonamento settimanale ricorrente",
    lockOrderSubmit: "Invia Ordine",
    totalAmount: "Importo Totale:",
    addBasket: "Aggiungi al carrello",
    noProductsActive: "Nessun prodotto è attualmente attivo nel menu di questa settimana. Torna presto!",
    bakingStatusProgress: "Stato Avanzamento Cottura",
    orderHash: "Ordine",
    orderedOn: "Ordinato il",
    collectionSlot: "Fascia Oraria di Ritiro",
    itemsOrdered: "Articoli Ordinati",
    recurringWeeklySubscription: "Abbonamento Settimanale Ricorrente",
    noOrdersPlaced: "Non hai ancora effettuato ordini. Sfoglia il nostro menu settimanale!",
    myProfileDetails: "Dettagli Mio Profilo",
    fullLegalName: "Nome e Cognome",
    phoneContact: "Numero di Telefono WhatsApp (es. +393451234567)",
    saveProfileDetails: "Salva Dettagli Profilo",
    activeSubscriptionsCustomer: "I Tuoi Abbonamenti Settimanali Attivi",
    recurringWeeklyItems: "Articoli Ricorrenti Settimanali",
    registeredOn: "Registrato il",
    noActiveSubsCustomer: "Non hai abbonamenti attivi. Seleziona \"Salva come abbonamento\" al checkout per abbonarti!",
    // Missing Customer Dashboard & Feedback Keys
    profileUpdatedSuccess: "Profilo aggiornato con successo!",
    profileUpdatedFailed: "Impossibile aggiornare il profilo",
    profileUpdateError: "Impossibile connettersi per aggiornare il profilo.",
    orderAndSubLockedIn: "Ordine e abbonamento settimanale bloccati! Benvenuto nel nostro club fisso.",
    orderSubmittedSuccess: "Ordine inviato con successo! I nostri panettieri si stanno preparando.",
    orderSubmitFailed: "Invio dell'ordine fallito",
    orderSubmitError: "Impossibile connettersi al motore di cottura. Riprova.",
    artisanMicrobakery: "Micro-panificio Artigianale",
    approved: "Approvato",
    bakingNextMonday: "Prossima cottura: lunedì mattina",
    bakedFreshOnDemand: "Cotto Fresco su Richiesta",
    menuNotPublished: "I panettieri non hanno ancora pubblicato il menu di questa settimana.",
    checkBackSoonLoaves: "Torna presto per pagnotte appena sfornate!",
    availableSizes: "Dimensioni Disponibili",
    myBakingBasket: "Il Mio Cestino da Forno",
    cartEmptyDesc: "Aggiungi le varianti dal menu a sinistra per iniziare a creare il tuo ordine.",
    saveAsStandingOrderDesc: "Salva come abbonamento settimanale ricorrente! Lo prenoteremo automaticamente ogni settimana se gli articoli sono attivi.",
    itemsCount: "Numero di Articoli",
    lockInAndSubscribe: "Blocca e Abbonati",
    orderStatusHistory: "Stato Ordini e Cronologia",
    noOrdersPlacedDesc: "Una volta ordinato il pane, il progresso sarà tracciato qui in tempo reale!",
    bakingBatch: "Lotto di Cottura",
    queuedAwaitingBatching: "In coda (In attesa di raggruppamento)",
    pendingStatus: "In attesa",
    confirmedStatus: "Confermato",
    inOvenStatus: "Nel forno",
    readyStatus: "Pronto",
    orderDetailsCount: "Dettagli Ordine ({count} articoli)",
    phoneContactDesc: "Consente al panettiere di scriverti direttamente su WhatsApp quando la tua pagnotta è fresca di forno!",
    // WhatsApp Helper Modal Keys
    whatsappHelperTitle: "Assistente Notifiche WhatsApp",
    orderIdLabel: "ID Ordine: {id}",
    noPhoneConfigured: "⚠️ Nessun numero di telefono configurato per questo utente.",
    selectScriptTemplate: "Seleziona Modello Messaggio",
    orderConfirmedTemplate: "Ordine Confermato",
    bakingNowTemplate: "In Cottura Ora",
    readyForPickupTemplate: "Pronto per il Ritiro",
    editPrefilledMessage: "Modifica Messaggio Precompilato",
    sendToWhatsapp: "Invia su WhatsApp",
    // WhatsApp Messages Template Keys
    whatsappConfirmedMessage: "Ciao {name}! 🍞 Il tuo ordine #{id} è stato confermato. Stiamo preparando le tue delizie artigianali ({items}) per la fascia oraria: {slot}! A presto! 🥖",
    whatsappBakingMessage: "Ciao {name}! 🔥 Volevamo solo informarti che il tuo pane ({items}) è nel forno proprio ora! Profuma moltissimo e sarà pronto per il ritiro nella tua fascia oraria: {slot}. 🥐",
    whatsappReadyMessage: "Ciao {name}! 🎉 Ottime notizie - i tuoi prodotti appena sfornati ({items}) sono pronti! 🥖 Caldi, croccanti e pronti per il ritiro nella tua fascia oraria: {slot}. A presto! ✨",
    whatsappGroupedConfirmedMessage: "Ciao {name}! 🍞 I tuoi ordini per il {date} sono confermati! Stiamo preparando le tue delizie artigianali ({items}) per la fascia oraria: {slot}! A presto! 🥖",
    whatsappGroupedBakingMessage: "Ciao {name}! 🔥 Volevamo solo informarti che il tuo pane ({items}) è nel forno proprio ora! Profuma moltissimo e sarà pronto per il ritiro nella tua fascia oraria: {slot}. 🥐",
    whatsappGroupedReadyMessage: "Ciao {name}! 🎉 Ottime notizie - i tuoi ordini ({items}) sono pronti! 🥖 Caldi, croccanti e pronti per il ritiro nella tua fascia oraria: {slot}. A presto! ✨",
    addInternalOrderBtn: "Aggiungi ordine interno",
    addInternalOrderTitle: "Aggiungi nuovo ordine interno / ospite",
    customerInfo: "Dettagli cliente",
    guestName: "Nome ospite / Soprannome",
    guestPhone: "Numero di telefono (Opzionale - per WhatsApp)",
    guestEmail: "Indirizzo e-mail (Opzionale)",
    itemsAndQuantities: "Prodotti e quantità",
    selectProductVariant: "Seleziona prodotto e dimensione...",
    addAnotherItem: "＋ Aggiungi un altro prodotto",
    submitOrder: "Invia ordine",
    internalOrderSuccess: "Ordine interno aggiunto con successo!",
    internalOrderFailed: "Impossibile inviare l'ordine interno. Controlla i dettagli.",
    settings: "Impostazioni",
    bakingDaysConfig: "Configurazione giorni di cottura",
    bakingDaysDesc: "Seleziona in quali giorni della settimana sforni. I clienti vedranno le prossime date per questi giorni al momento del pagamento.",
    searchPlaceholder: "Cerca ordini per nome cliente o numero...",
    settingsSaved: "Impostazioni salvate con successo!",
    changeBakingDay: "Cambia giorno di cottura",
    selectNewDate: "Seleziona nuova data di cottura",
    saveChanges: "Salva modifiche",
    leadTimeHoursLabel: "Tempo massimo per gli ordini",
    leadTimeHoursDesc: "Imposta quante ore prima del giorno di cottura un cliente può effettuare un ordine. Se impostato su 72 ore (3 giorni), una cottura del martedì mattina scade il sabato mattina.",
    hoursLabel: "{hours} ore",
    lastCallDeadlines: "Assistente di calcolo: Scadenze dell'ultimo bando",
    lastCallDeadlinesDesc: "Scadenze calcolate per ogni giorno di cottura attivo in base alle ore configurate (assumendo che la cottura inizi alle 06:00 del mattino di quel giorno):",
    bakingDay: "Giorno di cottura",
    lastCallDeadline: "Scadenza dell'ultimo bando",
    loyaltyTracker: "Programma fedeltà",
    loyaltyTrackerDesc: "Monitora i traguardi di acquisto degli utenti e i riscatti dei premi. Per ogni 10 articoli acquistati in ordini COMPLETATI, il cliente guadagna 1 pagnotta gratuita.",
    loyaltyRewardsTitle: "🏆 Tessera fedeltà Sourdough",
    loyaltyProgress: "Progresso fedeltà",
    totalBought: "Totale acquistato",
    freeEarned: "Omaggi guadagnati",
    freeRedeemed: "Riscattati",
    freeRemaining: "Rimanenti",
    stampsRemaining: "Mancano {stamps} timbri alla tua prossima pagnotta gratuita!",
    stampCardSubtitle: "Ogni 10 pagnotte di sourdough acquistate, la prossima la offriamo noi!",
    claimInstruction: "Mostra questa schermata al panettiere per riscattare la tua pagnotta gratuita!",
    redeemLoaf: "Riscatta pagnotta gratuita",
    redeemLoafSuccess: "Pagnotta gratuita riscattata con successo!",
    redeemLoafError: "Impossibile riscattare: nessun omaggio rimanente.",
    customerLedger: "Il mio libro del pane",
    customerLedgerDesc: "Il registro dei tuoi acquisti completati:",
    dateLabel: "Data",
    productLabel: "Prodotto",
    quantityLabel: "Qtà",
    itemLabel: "Articolo",
    userLoyaltyProgress: "Progresso fedeltà utente",
    loyaltyActionRedeem: "Segna 1 pagnotta come riscattata",
    viewHistory: "Visualizza cronologia",
    searchByClient: "Cerca per nome cliente, telefono o email...",
    freeLoafCount: "Pagnotta gratuita",
    freeLoavesCount: "Pagnotte gratuite",
    remainingLabel: "Rimanenti",
    couponsAvailableTitle: "🎁 Buoni fedeltà disponibili",
    couponsAvailableDesc: "Hai {count} buono/i per pagnotta gratuita pronti da riscattare! Applicali di seguito sui prodotti nel carrello.",
    applyCouponBtn: "🎁 Usa buono",
    appliedCouponPill: "🎁 Buono applicato",
    couponDiscounted: "Scontato con buono",
    freeLoafBadge: "🎁 PAGNOTTA GRATUITA",
    discountedText: "Scontato"
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('artisan_bakery_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('artisan_bakery_lang', currentLanguage);
  }, [currentLanguage]);

  const t = (key, params = {}) => {
    let val = translations[currentLanguage]?.[key] || translations['en']?.[key] || params.defaultValue || key;
    const replaceParams = { ...params };
    delete replaceParams.defaultValue;
    Object.entries(replaceParams).forEach(([k, v]) => {
      val = String(val).replace(`{${k}}`, v);
    });
    return val;
  };

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setCurrentLanguage(lang);
    }
  };

  // Sleek selector UI component
  const LanguageSwitcher = () => {
    return (
      <div className="flex items-center gap-1 p-1 bg-white/20 dark:bg-slate-900/30 backdrop-blur-md rounded-xl border border-slate-200/50 dark:border-slate-800/50 shadow-sm no-print">
        {[
          { code: 'en', flag: '🇬🇧', label: 'EN' },
          { code: 'hr', flag: '🇭🇷', label: 'HR' },
          { code: 'it', flag: '🇮🇹', label: 'IT' }
        ].map(l => (
          <button
            key={l.code}
            onClick={() => setLanguage(l.code)}
            className={`flex items-center gap-1 px-2.5 py-1 rounded-lg text-[10px] font-black tracking-wider transition ${
              currentLanguage === l.code
                ? 'bg-bakery-500 text-white shadow shadow-bakery-500/20'
                : 'text-slate-600 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800/40'
            }`}
          >
            <span>{l.flag}</span>
            <span>{l.label}</span>
          </button>
        ))}
      </div>
    );
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, t, setLanguage, LanguageSwitcher }}>
      {children}
    </LanguageContext.Provider>
  );
};
